site_name: Pocket Lab
pages:
  - Home: index.md
  - Commands: commands.md
  - Architecture: architecture.md
  - Libraries: libraries.md
  - Roadmap: roadmap.md
markdown_extensions: [ footnotes, smarty, abbr ]