''' A Command Line Tool for Managing Laboratory Projects '''
__author__ = 'rcj1492'
__created__ = '2016.03'
__command__ = 'lab'
__entry__ = 'lab = pocketlab.cli:cli'
__version__ = '0.3'
__module__ = 'pocketlab'
__license__ = 'MIT'
__team__ = 'Collective Acuity'
__email__ = 'support@collectiveacuity.com'
__url__ = 'https://github.com/collectiveacuity/pocketLab'
__order__ = [ 'home', 'init', 'list', 'update', 'remove', 'clean' ]
__description__ = 'A Command Line Tool for Managing Laboratory Projects'