__author__ = 'rcj1492'
__created__ = '2016.03'
__command__ = 'lab'
__version__ = '0.1'
__module__ = 'pocketLab'
__license__ = 'MIT'
__team__ = 'Collective Acuity'
__email__ = 'support@collectiveacuity.com'